on:
  push:
  pull_request:
  schedule:
    - cron: '13 4 * * *'
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'quay.io/pypa/manylinux2014_x86_64:2021-02-07-8435c06'
          - 'quay.io/pypa/manylinux2014_x86_64:2021-02-07-8cce88b'
          - 'quay.io/pypa/manylinux2014_x86_64:2021-02-06-93da623'
        py:
          - 'cp39-cp39'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2

      - name: Build Wheel
        run: |
          docker run -e PYPATH=/opt/python/${{ matrix.py }} -e ZSTD_WARNINGS_AS_ERRORS=1 --rm -v `pwd`:/project ${{ matrix.image }} /project/ci/build-manylinux-wheel.sh

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          path: dist
